image: Visual Studio 2022
environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"
      TOX_ENV: "py310"
    - PYTHON: "C:\\Python311-x64"
      TOX_ENV: "py311"
    - PYTHON: "C:\\Python312-x64"
      TOX_ENV: "py312"
    - PYTHON: "C:\\Python313-x64"
      TOX_ENV: "py313"
    - PYTHON: "C:\\Python314-x64"
      TOX_ENV: "py314"


init:
  - "%PYTHON%\\python -V"
  - "%PYTHON%\\python -c \"import struct;print(8 * struct.calcsize('P'))\""

install:
  - "%PYTHON%\\python -m pip install --upgrade pip tox"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%\\python -m tox -e %TOX_ENV%"
