from datetime import date

from .__about__ import __author__, __version__
from .algorithms import (
    DoubleExponentialMovingAverage,
    ExponentialMovingAverage,
    SmoothingAlgorithm,
)
from .bar import DataTransferBar, NullBar, ProgressBar
from .base import UnknownLength
from .multi import MultiBar, SortKey
from .shortcuts import progressbar
from .terminal.stream import LineOffsetStreamWrapper
from .utils import len_color, streams
from .widgets import (
    ETA,
    AbsoluteETA,
    AdaptiveETA,
    AdaptiveTransferSpeed,
    AnimatedMarker,
    Bar,
    BouncingBar,
    Counter,
    CurrentTime,
    DataSize,
    DynamicMessage,
    FileTransferSpeed,
    FormatCustomText,
    FormatLabel,
    FormatLabelBar,
    GranularBar,
    JobStatusBar,
    MultiProgressBar,
    MultiRangeBar,
    Percentage,
    PercentageLabelBar,
    Postfix,
    ReverseBar,
    RotatingMarker,
    SimpleProgress,
    SmoothingETA,
    Timer,
    UnitProgress,
    Variable,
    VariableMixin,
)

__date__ = str(date.today())
__all__ = [
    'ETA',
    'AbsoluteETA',
    'AdaptiveETA',
    'AdaptiveTransferSpeed',
    'AnimatedMarker',
    'Bar',
    'BouncingBar',
    'Counter',
    'CurrentTime',
    'DataSize',
    'DataTransferBar',
    'DoubleExponentialMovingAverage',
    'DynamicMessage',
    'ExponentialMovingAverage',
    'FileTransferSpeed',
    'FormatCustomText',
    'FormatLabel',
    'FormatLabelBar',
    'GranularBar',
    'JobStatusBar',
    'LineOffsetStreamWrapper',
    'MultiBar',
    'MultiProgressBar',
    'MultiRangeBar',
    'NullBar',
    'Percentage',
    'PercentageLabelBar',
    'Postfix',
    'ProgressBar',
    'ReverseBar',
    'RotatingMarker',
    'SimpleProgress',
    'SmoothingAlgorithm',
    'SmoothingETA',
    'SortKey',
    'Timer',
    'UnitProgress',
    'UnknownLength',
    'Variable',
    'VariableMixin',
    '__author__',
    '__version__',
    'len_color',
    'progressbar',
    'streams',
]
